# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DataFrameToGraphML <- function(nodes, edges, nodeIdCol = "id", parentIdCol = NA_character_, sourceCol = "source", targetCol = "target", nodeAttrs = as.character( c()), edgeAttrs = as.character( c()), isDirected = FALSE) {
    .Call('_RGraphML_DataFrameToGraphML', PACKAGE = 'RGraphML', nodes, edges, nodeIdCol, parentIdCol, sourceCol, targetCol, nodeAttrs, edgeAttrs, isDirected)
}

DataFrameToTulip <- function(nodes, edges, nodeIdCol = "id", parentIdCol = NA_character_, edgeIdCol = "id", sourceCol = "source", targetCol = "target", nodeAttrs = as.character( c()), edgeAttrs = as.character( c()), isDirected = FALSE) {
    .Call('_RGraphML_DataFrameToTulip', PACKAGE = 'RGraphML', nodes, edges, nodeIdCol, parentIdCol, edgeIdCol, sourceCol, targetCol, nodeAttrs, edgeAttrs, isDirected)
}

